/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hacker_room_low_poly.glb --types -T --keepmeshes -s --keepmaterials 
Files: hacker_room_low_poly.glb [6.64MB] > C:\Users\Kenzo Dewaegenaere\development\projects\pp\src\assets\Models\Landing\hacker_room_low_poly-transformed.glb [1.06MB] (84%)
Author: Pudding_King (https://sketchfab.com/Pudding_King)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hacker-room-low-poly-2d86dd3e18a44cc080f85a0e1af9ffe9
Title: Hacker Room low poly
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube2_hard_disclambert2_0: THREE.Mesh
    pCube62_hard_disclambert2_0: THREE.Mesh
    pCube7_lambert4_0: THREE.Mesh
    pCube13_lambert4_0: THREE.Mesh
    ouden_tvpCube1_lambert4_0: THREE.Mesh
    pCube14_lambert6_0: THREE.Mesh
    pCube53_lambert9_0: THREE.Mesh
    pCube54_lambert9_0: THREE.Mesh
    pCube55_lambert9_0: THREE.Mesh
    ercopCube1_lambert9_0: THREE.Mesh
    pCube57_lambert11_0: THREE.Mesh
    pCube58_lambert11_0: THREE.Mesh
    PC1pCube1_lambert11_0: THREE.Mesh
    kamerpCube1_lambert1_0: THREE.Mesh
    texttypeMesh1_texttypeShader2_0: THREE.Mesh
    tafelpCube1_lambert3_0: THREE.Mesh
    tafelpCube2_lambert2_0: THREE.Mesh
    papierenpCube1_lambert6_0: THREE.Mesh
    muispCube1_lambert7_0: THREE.Mesh
    toetsen_boardpCube1_lambert10_0: THREE.Mesh
    stoelpCube1_stoellambert4_0: THREE.Mesh
    stoelpCube2_stoellambert2_0: THREE.Mesh
    stoelpCylinder1_stoellambert3_0: THREE.Mesh
    stoelpTorus1_stoellambert6_0: THREE.Mesh
    stoelpTorus1_lambert1_0: THREE.Mesh
    stoelpCube3_stoellambert2_0: THREE.Mesh
    giant_robotpPlane1_giant_robotlambert2_0: THREE.Mesh
    swaardenpPlane1_swaardenlambert2_0: THREE.Mesh
    showerpPlane1_showerlambert2_0: THREE.Mesh
    whalepPlane1_whalelambert2_0: THREE.Mesh
    astronautpPlane1_astronautlambert2_0: THREE.Mesh
    blood_forestpPlane1_blood_forestlambert2_0: THREE.Mesh
    pCube1_hard_disclambert2_0: THREE.Mesh
    pCube8_doos_1lambert2_0: THREE.Mesh
    pCube15_lambert6_0: THREE.Mesh
    pCube38_lambert8_0: THREE.Mesh
    pCylinder1_blikielambert2_0: THREE.Mesh
    pCube49_tvlambert2_0: THREE.Mesh
  }
  materials: {
    hard_disclambert2: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert6: THREE.MeshStandardMaterial
    lambert9: THREE.MeshStandardMaterial
    lambert11: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    texttypeShader2: THREE.MeshStandardMaterial
    lambert3: THREE.MeshStandardMaterial
    lambert2: THREE.MeshStandardMaterial
    lambert7: THREE.MeshStandardMaterial
    lambert10: THREE.MeshStandardMaterial
    stoellambert4: THREE.MeshStandardMaterial
    stoellambert2: THREE.MeshStandardMaterial
    stoellambert3: THREE.MeshStandardMaterial
    stoellambert6: THREE.MeshStandardMaterial
    giant_robotlambert2: THREE.MeshStandardMaterial
    swaardenlambert2: THREE.MeshStandardMaterial
    showerlambert2: THREE.MeshStandardMaterial
    whalelambert2: THREE.MeshStandardMaterial
    astronautlambert2: THREE.MeshStandardMaterial
    blood_forestlambert2: THREE.MeshStandardMaterial
    doos_1lambert2: THREE.MeshStandardMaterial
    lambert8: THREE.MeshStandardMaterial
    blikielambert2: THREE.MeshStandardMaterial
    tvlambert2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hacker_room_low_poly-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pCube2_hard_disclambert2_0.geometry} material={materials.hard_disclambert2} position={[0.138, 0.588, -0.357]} rotation={[1.765, -0.004, 0.089]} scale={[0.119, 0.119, 0.013]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube62_hard_disclambert2_0.geometry} material={materials.hard_disclambert2} position={[0.816, 0.253, 1.412]} rotation={[1.765, -0.004, 0.089]} scale={[0.119, 0.119, 0.013]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube7_lambert4_0.geometry} material={materials.lambert4} position={[-0.923, 0.259, 1.316]} rotation={[0, 0.703, 0]} scale={0.465} />
      <mesh castShadow receiveShadow geometry={nodes.pCube13_lambert4_0.geometry} material={materials.lambert4} position={[-0.487, 0.703, 1.506]} rotation={[0.447, 1.246, -0.427]} scale={0.465} />
      <mesh castShadow receiveShadow geometry={nodes.ouden_tvpCube1_lambert4_0.geometry} material={materials.lambert4} position={[0.949, 0.259, -1.484]} rotation={[-Math.PI, -0.909, -Math.PI]} scale={0.465} />
      <mesh castShadow receiveShadow geometry={nodes.pCube14_lambert6_0.geometry} material={materials.lambert6} position={[-0.929, 0.51, 1.243]} rotation={[3.118, -0.199, 0]} scale={[0.318, 0.011, 0.234]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube53_lambert9_0.geometry} material={materials.lambert9} position={[0.712, 2.055, -1.659]} scale={[0.821, 0.35, 0.195]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube54_lambert9_0.geometry} material={materials.lambert9} position={[-1.119, 2.055, 1.327]} rotation={[0, 1.56, 0]} scale={[0.821, 0.35, 0.195]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube55_lambert9_0.geometry} material={materials.lambert9} position={[-1.107, 2.055, 0.5]} rotation={[0, 1.56, 0]} scale={[0.821, 0.35, 0.195]} />
      <mesh castShadow receiveShadow geometry={nodes.ercopCube1_lambert9_0.geometry} material={materials.lambert9} position={[-0.117, 2.055, -1.659]} scale={[0.821, 0.35, 0.195]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube57_lambert11_0.geometry} material={materials.lambert11} position={[0.112, 0.111, -0.295]} rotation={[Math.PI / 2, 0, 1.62]} scale={[0.362, 0.362, 0.173]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube58_lambert11_0.geometry} material={materials.lambert11} position={[-1.014, 0.65, -0.084]} rotation={[-1.576, 0.019, 0.066]} scale={[0.362, 0.362, 0.173]} />
      <mesh castShadow receiveShadow geometry={nodes.PC1pCube1_lambert11_0.geometry} material={materials.lambert11} position={[-0.135, 0.208, -1.664]} rotation={[0, -0.009, 0]} scale={[0.362, 0.362, 0.173]} />
      <mesh castShadow receiveShadow geometry={nodes.kamerpCube1_lambert1_0.geometry} material={materials.lambert1} position={[0, 1.047, 0]} scale={[2.362, 2.035, 3.505]} />
      <mesh castShadow receiveShadow geometry={nodes.texttypeMesh1_texttypeShader2_0.geometry} material={materials.texttypeShader2} position={[0, 1.125, -1.76]} rotation={[0, 0, -0.18]} scale={[0.322, 0.237, 0.073]} />
      <mesh castShadow receiveShadow geometry={nodes.tafelpCube1_lambert3_0.geometry} material={materials.lambert3} position={[-0.424, 0.552, -0.186]} rotation={[0, 1.555, 0]} scale={[0.629, 0.037, 1.533]} />
      <mesh castShadow receiveShadow geometry={nodes.tafelpCube2_lambert2_0.geometry} material={materials.lambert2} position={[0.325, 0.253, -0.343]} rotation={[1.856, -1.162, 1.879]} scale={[0.48, 0.684, 0.062]} />
      <mesh castShadow receiveShadow geometry={nodes.papierenpCube1_lambert6_0.geometry} material={materials.lambert6} position={[-0.929, 0.501, 1.243]} rotation={[3.118, 0, 0]} scale={[0.318, 0.011, 0.234]} />
      <mesh castShadow receiveShadow geometry={nodes.muispCube1_lambert7_0.geometry} material={materials.lambert7} position={[-0.939, 0.582, -0.421]} rotation={[Math.PI, 0.809, 0]} scale={[0.121, 0.038, 0.121]} />
      <mesh castShadow receiveShadow geometry={nodes.toetsen_boardpCube1_lambert10_0.geometry} material={materials.lambert10} position={[-0.526, 0.567, -0.246]} rotation={[0, 1.039, 0]} scale={[0.229, 0.019, 0.522]} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpCube1_stoellambert4_0.geometry} material={materials.stoellambert4} position={[-0.196, 0.45, -1.185]} rotation={[-0.061, 1.126, 0]} scale={[0.652, 0.02, 0.073]} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpCube2_stoellambert2_0.geometry} material={materials.stoellambert2} position={[-0.8, 0.491, -1.05]} rotation={[-0.061, 1.126, 0]} scale={[0.483, 0.04, 0.483]} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpCylinder1_stoellambert3_0.geometry} material={materials.stoellambert3} position={[-0.359, 0.275, -0.937]} scale={[0.135, 0.234, 0.135]} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpTorus1_stoellambert6_0.geometry} material={materials.stoellambert6} position={[-0.354, 0.053, -0.936]} rotation={[-Math.PI, -1.542, -Math.PI]} scale={0.05} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpTorus1_lambert1_0.geometry} material={materials.lambert1} position={[-0.354, 0.053, -0.936]} rotation={[-Math.PI, -1.542, -Math.PI]} scale={0.05} />
      <mesh castShadow receiveShadow geometry={nodes.stoelpCube3_stoellambert2_0.geometry} material={materials.stoellambert2} position={[0.269, 0.863, -1.075]} rotation={[3.082, -1.142, 1.845]} scale={[0.483, 0.04, 0.483]} />
      <mesh castShadow receiveShadow geometry={nodes.giant_robotpPlane1_giant_robotlambert2_0.geometry} material={materials.giant_robotlambert2} position={[-1.176, 1.085, 1.387]} rotation={[1.511, 0, -Math.PI / 2]} scale={[0.498, 0.652, 1.369]} />
      <mesh castShadow receiveShadow geometry={nodes.swaardenpPlane1_swaardenlambert2_0.geometry} material={materials.swaardenlambert2} position={[-1.158, 1.333, 0.831]} rotation={[1.644, 0, -Math.PI / 2]} scale={[0.521, 1.295, 0.777]} />
      <mesh castShadow receiveShadow geometry={nodes.showerpPlane1_showerlambert2_0.geometry} material={materials.showerlambert2} position={[-0.763, 0.913, -1.723]} rotation={[Math.PI / 2, -0.066, 0]} scale={[0.516, 0.489, 0.745]} />
      <mesh castShadow receiveShadow geometry={nodes.whalepPlane1_whalelambert2_0.geometry} material={materials.whalelambert2} position={[-0.094, 0.84, -1.747]} rotation={[Math.PI / 2, -0.157, 0]} scale={[0.414, 0.392, 0.598]} />
      <mesh castShadow receiveShadow geometry={nodes.astronautpPlane1_astronautlambert2_0.geometry} material={materials.astronautlambert2} position={[-0.507, 0.686, -1.715]} rotation={[Math.PI / 2, 0.045, 0]} scale={[0.528, 0.528, 0.791]} />
      <mesh castShadow receiveShadow geometry={nodes.blood_forestpPlane1_blood_forestlambert2_0.geometry} material={materials.blood_forestlambert2} position={[-1.161, 0.682, 0.64]} rotation={[1.471, 0, -Math.PI / 2]} scale={[0.516, 0.516, 0.978]} />
      <instancedMesh args={[nodes.pCube1_hard_disclambert2_0.geometry, materials.hard_disclambert2, 17]} castShadow receiveShadow instanceMatrix={nodes.pCube1_hard_disclambert2_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube8_doos_1lambert2_0.geometry, materials.doos_1lambert2, 12]} castShadow receiveShadow instanceMatrix={nodes.pCube8_doos_1lambert2_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube15_lambert6_0.geometry, materials.lambert6, 14]} castShadow receiveShadow instanceMatrix={nodes.pCube15_lambert6_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube38_lambert8_0.geometry, materials.lambert8, 7]} castShadow receiveShadow instanceMatrix={nodes.pCube38_lambert8_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCylinder1_blikielambert2_0.geometry, materials.blikielambert2, 23]} castShadow receiveShadow instanceMatrix={nodes.pCylinder1_blikielambert2_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube49_tvlambert2_0.geometry, materials.tvlambert2, 5]} castShadow receiveShadow instanceMatrix={nodes.pCube49_tvlambert2_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/hacker_room_low_poly-transformed.glb')
